version: '2'
services:
  yocto:
    build: ./docker-conf
    container_name: yocto
    restart: always
    volumes:
      - ./container/home/yocto:/home/yocto
      - ./container/opt:/opt

volumes:
  yocto:
    driver: local

